version: '3.9'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ambassador'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - '33066:3306'
  redis:
    image: redis:5.0.3-alpine
    restart: always
    ports:
      - '63679:6379'
  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none' # disable saving logs
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
