version: '3.9'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'admin'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - '33066:3306'
